HSC-186: Add New Maxillofacial Surgical Procedures
CRUDEM/openmrs-config-hsc pull request #55
Opened 2023-07-14 11:30 UTC by nuhuhmutebi

2023-07-17 15:26 UTC, rbuisson approved these changes

2023-07-17 15:28 UTC, rbuisson requested changes

2023-07-17 15:28 UTC, rbuisson commented on configuration/concepts/orders_maxillofacial.csv
> +88333bde-fe5f-4d5e-8e2a-1775e7d14166,,,Fracture Mandibulaire,Fracture Mandibulaire,Fracture Mandibulaire,Fracture Mandibulaire,,,Maxillofacial,Text,,,,,,,,,,,
Fracture mandibulaire

2023-07-17 15:28 UTC, rbuisson commented on configuration/concepts/orders_maxillofacial.csv
> +aa50f047-f4a5-4a88-9f96-c8a7c808420d,,,Fracture Zygomatique,Fracture Zygomatique,Fracture Zygomatique,Fracture Zygomatique,,,Maxillofacial,Text,,,,,,,,,,,
Fracture zygomatique

2023-07-20 07:22 UTC, nuhuhmutebi commented on configuration/concepts/orders_maxillofacial.csv
> +aa50f047-f4a5-4a88-9f96-c8a7c808420d,,,Fracture Zygomatique,Fracture Zygomatique,Fracture Zygomatique,Fracture Zygomatique,,,Maxillofacial,Text,,,,,,,,,,,
Done

2023-07-20 07:22 UTC, nuhuhmutebi commented on configuration/concepts/orders_maxillofacial.csv
> +88333bde-fe5f-4d5e-8e2a-1775e7d14166,,,Fracture Mandibulaire,Fracture Mandibulaire,Fracture Mandibulaire,Fracture Mandibulaire,,,Maxillofacial,Text,,,,,,,,,,,
Done

2023-07-20 13:40 UTC, merged